[Hart85] Fix Future Warning: ChainedAssigmentError (#1011)
* [Hart85] Fix Future Warning: ChainedAssigmentError

hart_85.py:308: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

A typical example is when you are setting values in a column of a
DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the
assignment in a single step and ensure this keeps updating the original
`df`.

* [Hart85] Fix UnicodeDecodeError

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 164: character maps to <undefined>

In Python3, the pickle module expects the underlying file objects to accept or return bytes

	pickle_in = open(filename, 'rb')